cache:
  directories:
  - $HOME/.m2
branches:
  only:
  - master
language: java
jdk:
  - openjdk8
before_install:
  - whoami && printenv
install:
  - mvn clean install -B -V
script:
  - docker-compose up || travis_terminate 0
