cache:
  directories:
  - $HOME/.m2
branches:
  only:
  - master
language: java
jdk:
  - openjdk8
before_install:
  - whoami && printenv
script:
  - chmod +x run.sh && bash run.sh
cron:
  - branch: master
    nterval: monthly
       options: always run
